include theme.conf

font_family JetBrainsMono Nerd Font
font_size 10
background_opacity 0.95
enable_audio_bell no
enabled_layouts tall,splits,fat,grid,stack

map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0
map ctrl+shift+backspace change_font_size all 0

map super+c copy_to_clipboard
map super+v paste_from_clipboard

confirm_os_window_close 1
